name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: lrydzkowski/async-jobs-template-api
  REACT_FRONTEND_IMAGE_NAME: lrydzkowski/async-jobs-template-react-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Generate version tag
        run: echo "VERSION_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Show the version tag
        run: echo ${{ env.VERSION_TAG }}

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK 9
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Install API dependencies
        run: dotnet restore

      - name: Restore .NET tools
        run: dotnet tool restore --tool-manifest AsyncJobsTemplate.WebApi/.config/dotnet-tools.json

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Run API tests
        run: dotnet test --no-restore --verbosity normal

      - name: Sign in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API docker image
        id: docker_api_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./AsyncJobsTemplate.WebApi/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Build React frontend app docker image
        id: docker_frontend_app_build
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend/async-jobs-template-react-front/
          file: ./Frontend/async-jobs-template-react-front/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REACT_FRONTEND_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.REACT_FRONTEND_IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Set tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.VERSION_TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

    outputs:
      version_tag: ${{ env.VERSION_TAG }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'dev'

    steps:
      - name: Echo version tag
        run: echo ${{ needs.build.outputs.version_tag }}

      - name: Deploy API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://v2.r-systems-cloud.com/api/hooks/async-jobs-template-api'
          method: 'GET'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_API_KEY }}"}'
          timeout: 300000

      - name: Deploy React frontend app
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://v2.r-systems-cloud.com/api/hooks/async-jobs-template-react-front'
          method: 'GET'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_REACT_FRONT_KEY }}"}'
          timeout: 300000
